[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sample = "7WEsVmbRMFMJ5TXBuauiQRA7BLU7sgGj6ytZLdShvVme"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
